### ISSUE TITLE
Unable to access rest API's. Always throws authorisation Failure

### ISSUE THREAD

**Issue by saurabhsuman2111** [Homas/ioc2rpz#16]
I have configured the ioc2rpz and ioc2rpz.gui following the instruction. Now whenever I try to hit the REST API's it always results into failure. I have tried with all the TSIG keys configured, but always getting the same error response.
I don't know if its a bug or I am missing something, I need immediate help on this hence I am posting here. Any kind of help would be highly appreciated. 

Here is the curl verbose output:
*   Trying XX.XXX.XXX.XXX:8443...
* TCP_NODELAY set
* Connected to XX.XXX.XXX.XXX (XX.XXX.XXX.XXX) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=xx; ST=xxx; L=xxx; O=xxxxxx; OU=xxx; CN=xxxxxx.com; emailAddress=xxxx@xxxx.com
*  start date: Aug 22 05:29:52 2019 GMT
*  expire date: Aug 21 05:29:52 2020 GMT
*  issuer: C=xx; ST=xx; L=xxx; O=xxxxx; OU=xx; CN=xxxxx.com; emailAddress=xxxxx@xxxxxx.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Server auth using Basic with user 'xxxxxxxxxxx'
* Using Stream ID: 1 (easy handle 0x556ceabd3540)
> GET /api/v1.0/feed/dns-bh.ioc2rpz HTTP/2
> Host: XX.XXX.XXX.XXX:8443
> Authorization: Basic YXdzX21nbW50X2tleV8yOkI2UjBTc3cxcjBxVzQ1eGJqR0RhUU85NngzN1pjT1g5L0JqckF3Qkt5ejQ9
> User-Agent: curl/7.65.1
> Accept: text/plain
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
< HTTP/2 401 
HTTP/2 401 
< content-length: 48
content-length: 48
< date: Fri, 23 Aug 2019 10:55:02 GMT
date: Fri, 23 Aug 2019 10:55:02 GMT
< server: Cowboy
server: Cowboy
* Authentication problem. Ignoring this.
< www-authenticate: Basic
www-authenticate: Basic

< 
{status: "error", msg: "Authentication failed"}
* Connection #0 to host XX.XXX.XXX.XXX left intact

**Comment by saurabhsuman2111** [comment]
This is the curl command that I am using:
curl -v -i -u "xxx_xxx_xxx_1:Zk3Lv0mu4wefKoM9C7Y5hQ==" --insecure -H "Accept: text/plain" https://XX.XXX.XXX.XXX:8443/api/v1.0/feed/dns-bh.ioc2rpz

**Comment by Homas** [comment]
Hi,

W/o looking on the ioc2rpz logs it is hard to say. 
There are 2 possible options:
- your management station IP is not provisioned in ACL;
- ioc2rpz was started first and doesn't have a configuration;

BR,
Vadim

**Comment by saurabhsuman2111** [comment]
Thanks for the reply.. it helped to resolve the issue.
