### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by gatsukito** [Homas/ioc2rpz#20]
## Steps
1.  Fill /opt/ioc2rpz/cfg/whitelist1.txt with "yellowcabnc.com"
1.  Add whitelist into RPZ with IOC Source it blocks "yellowcabnc.com"
1.  Publish configuration
1.  Export BIND configuration
1.  Update your BIND 9 server
1.  You use dig or connect to BIND 9 from your PC and you do http request to "yellowcabnc.com". The site is down with NXDOMAIN response

How can I do than whitelist allows me to do http request to "yellowcabnc.com"?

**Comment by Homas** [comment]
Thanks for reporting!
I've fixed the bug in the "dev" branch. 
I'll need to make a few tests before moving it to the "master" branch.

**Comment by gatsukito** [comment]
Thanks you. ioc2rpz is a big tool and I love it

**Comment by Homas** [comment]
Thanks! I've pushed the patch to the master branch.
