### ISSUE TITLE
Unsupported Actions

### ISSUE THREAD

**Issue by Yvtq8K3n** [Homas/ioc2rpz#27]
In the documentation it is presented the following actions:

> Action. Supported actions: nxdomain, nodata, passthru, drop, tcp-only, {"redirect_domain","example.com"}, {"redirect_ip","127.0.0.1"} and list of local records [{"local_aaaa","fe80::1"}, {"local_a","127.0.0.1"}, {"local_cname","www.example.com"}, {"local_txt","Text Record"}]. redirect_domain is an alias for local_cname. redirect_ip is an alias for local_a, local_aaaa;

Exploring ipc2orzp-gui it was not possible to perform the following actions:
- {"redirect_domain","example.com"} - No option
- {"redirect_ip","127.0.0.1"} - No option
- local records - Not parsing correctly

In regards to the actions label has No option the ioc2rpz-gui doesn't currently allow it.

Abording the action Local Records throught ioc2rpz-gui its identified a parsing issue presented bellow:
![image](https://user-images.githubusercontent.com/19397871/86805687-06224200-c070-11ea-92af-639c73cd15b7.png)

`local_cname www.test.com -> On config file appears has: ...,[{"local_cname www.test.com", ""},...`

**Comment by Homas** [comment]
Please take a look on the dev branch. It is fixed there. I'm wrapping up the development and will merge it to the master branch later this month.
