### ISSUE TITLE
curl request is giving "authentication failed" message

### ISSUE THREAD

**Issue by vijayb888** [Homas/ioc2rpz#37]
Hello developers,
I have installed the software using docker images and have the AXFR working with a TSIG key. But when I do the https request with the same key, I'm getting the following error.
`#  curl -i -u "tkey-3lu9dnuymu-89272zesfa:QVeIrOj5v+7Gk2NNyzpLxLEBlacXQ/KBASHMCGQfTKI="  --insecure  https://192.168.0.2:8443/api/v1.0/feed/notracking.ioc2rpz
HTTP/1.1 401 Unauthorized
content-length: 48
date: Tue, 20 Apr 2021 03:41:08 GMT
server: Cowboy
www-authenticate: Basic

{status: "error", msg: "Authentication failed"}`

**Comment by Homas** [comment]
You need to add the TSIG key to the list of the management IPs + provision ACL on the server.
Take a look on the srv record in the config.
