### ISSUE TITLE
Unable to load RPZ zone

### ISSUE THREAD

**Issue by dmgeurts** [Homas/ioc2rpz#41]
I thought I had it all working, then come back a few days later to find RPZ not working in PowerDNS-recursor. This is the error log I get:

`Dec 17 19:38:37 rdns1 pdns-recursor[3684822]: msg="Unable to load RPZ zone, will retry" subsystem="rpz" level=1 prio=4 ts="1639766317.724" exception="Packet (gambling.ioc2rpz|#252) has a TSIG record in an invalid position." from="10.1.1.1" refresh="10" zone="gambling.ioc2rpz"`

What on earth does "TSIG record in an invalid position" mean?

**Comment by Homas** [comment]
When did you pull ioc2rpz? Was it master or dev branch?

**Comment by dmgeurts** [comment]
Master (afaik). However, I think I've found the issue. When I check the size of the zone using an AXFR I see it's empty...

**Comment by Homas** [comment]
please pull the dev branch. I've made a few fixed couple of days ago. IXFR was broken.

**Comment by dmgeurts** [comment]
The regex on my source feed was broken.
