### ISSUE TITLE
Source error crashes ioc2rpz

### ISSUE THREAD

**Issue by dmgeurts** [Homas/ioc2rpz#49]
ioc2rpz wouldn't restart after a reboot of the server it was running on. It turns out that if a source does not return any usable data after the regex filter is applied. ioc2rpz throws a tantrum and crashes. The last log line before the crash dump indicates which source is the culprit, but it doesn't help identify why there was no content. Nor is it helpful to have the docker image crash as that takes all the other RPZ feeds down as well.

Maybe, ioc2rpz could ignore the issue with the source, disable the RPZ and log an error in the logs. If ioc2rpz.gui could subsequently show an alert, that would be the cherry on top.

That said. I can't work out why this source isn't returning anything, other than that it's using tabs instead of spaces.

**Comment by Homas** [comment]
Did u use the resent code? if not, please upgrade first.
The images on the docker hub are deprecated. 
Install docker compose (or docker version with it) and use [this](https://github.com/Homas/ioc2rpz.dc/blob/master/docker-compose.yml) docker compose configuration file

**Comment by dmgeurts** [comment]
Thank you, ioc2rpz.gui successfully built, but the ioc2rpz build failed: https://github.com/Homas/ioc2rpz.dc/issues/1

**Comment by dmgeurts** [comment]
Installing the docker-compose based images appears to have wiped the config. Is there a way I can import the old config rather than start over?

**Comment by dmgeurts** [comment]
After rebuilding both ioc2rpz and ioc2rpz.gui, I had to remove the latest source and RPZ that I added. I then recreated them and the configuration file was successfully built, no more crashes!
